config_map: 
  - name: OPENSHIFT_HOST_PORT
    value: "{{ openshift_host_port }}"
  - name: OPENSHIFT_USER
    value: "{{ openshift.username }}"
  - name: OPENSHIFT_PASSWORD
    value: "{{ openshift.password }}"    
  - name: GITHUB
    value: "{{ github.org }}"    
  - name: GITHUB_USER
    value: "{{ github.user }}"
  - name: GITHUB_PASSWORD
    value: "{{ github.password }}"
  - name: PRODUCT
    value: "{{ product.name }}"    
  - name: JBOSS_A_MQ_BROKER_URL
    value: "tcp://broker-amq-tcp.{{ project }}.svc:61616"
  - name: CONSOLE_FEATURE_API_JDBC_URL
    value: "jdbc:postgresql://postgresql.{{ project }}.svc:5432/{{ project }}-console-feature-api"
  - name: JAEGER_SERVICE_NAME
    value: "{{ project }}-console-environment-api"
  - name: JAEGER_SAMPLER_TYPE
    value: const
  - name: JAEGER_SAMPLER_PARAM
    value: 1
  - name: JAEGER_SAMPLER_MANAGER_HOST_PORT
    value: "jaeger-agent.{{ product.name }}-monitoring.svc:5778"    
  - name: JAEGER_AGENT_HOST
    value: "jaeger-agent.{{ product.name }}-monitoring.svc"    